In [4]:
import numpy as np 

a = np.array([[23,34],[344,54]])
print(np.append(a,4000))


[  23   34  344   54 4000]


In [6]:
print(np.insert(a, 1, 333))  #array, index, value 

print(np.insert(a, 1, [222, 333], axis = 1)) 


[ 23 333  34 344  54]
[[ 23 222  34]
 [344 333  54]]


In [8]:
print(np.delete(a,1))

[ 23 344  54]
