In [9]:
import numpy as np
a = np.array([1,2,3,4,32])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))  #number of 
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


42
1
32
5
8.4
[ 1  3  6 10 42]
[  1   2   6  24 768]


In [17]:
a = [100, 233, 250, 133,200]
b= [12,13,16,18,20]

price = np.array(a)
quantity = np.array(b)

print(price, "\n", quantity)

# print(np.sum(price))

p =  np.cumprod([price, quantity], axis = 0)

print (p)

[100 233 250 133 200] 
 [12 13 16 18 20]
[[ 100  233  250  133  200]
 [1200 3029 4000 2394 4000]]


In [ ]:
,