In [14]:
import numpy as np

a = [30, 50, 45], [60, 56, 48]
arr = np.array(a)
print(arr)
print(arr.shape)
print (len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)

print(arr.astype(float))

[[30 50 45]
 [60 56 48]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 50. 45.]
 [60. 56. 48.]]
