In [1]:
a = [30, 5, 89]
b = [65,78,45]
print(a+b)

[30, 5, 89, 65, 78, 45]


In [19]:
 #Concat
import numpy as np
arr1 = np.array([[2, 20],[34,30]])
arr2 = np.array([[4,5],[4,6]])

print(np.concatenate([arr1,arr2]))


[[ 2 20]
 [34 30]
 [ 4  5]
 [ 4  6]]


In [25]:
print(np.concatenate([arr1,arr2],axis = 1))  

# = 0   or vstack(arr1, arr2)
#[[ 2 20]  
# [34 30]
# [ 4  5]
#  [ 4  6]]

#if axis = 1   or hstack(arr1, arr2) 
#[[ 2 20  4  5]
 #[34 30  4  6]]



[[ 2 20  4  5]
 [34 30  4  6]]


In [29]:
a = np.array([34,56,34,56,54,55,23])
print(np.array_split(a,2))

#or
print("for indexing")
b = np.array_split(a,2)

print(b[1])

[array([34, 56, 34, 56]), array([54, 55, 23])]
for indexing
[54 55 23]
