In [6]:
import numpy as np

arr1 = np.array([[30,40],[4, 50]])
arr2 = np.array([[45,43] ,[45, 56]])

print(arr1 + arr2)

print(np.add(arr1, arr2))

[[ 75  83]
 [ 49 106]]
[[ 75  83]
 [ 49 106]]


In [12]:
import numpy as np

arr1 = np.array([[30,40],[4, 50]])
arr2 = np.array([[45,43] ,[45, 56]])

print(arr1 - arr2)
print("np.....:")
print(np.subtract(arr1, arr2))

[[-15  -3]
 [-41  -6]]
np.....:
[[-15  -3]
 [-41  -6]]


In [13]:
import numpy as np

arr1 = np.array([[30,40],[4, 50]])
arr2 = np.array([[45,43] ,[45, 56]])

print(arr1 / arr2)
print("np.....:")
print(np.divide(arr1, arr2))

[[0.66666667 0.93023256]
 [0.08888889 0.89285714]]
np.....:
[[0.66666667 0.93023256]
 [0.08888889 0.89285714]]


In [14]:
import numpy as np

arr1 = np.array([30,40])
print(np.sqrt(arr1))

[5.47722558 6.32455532]
