In [3]:
import numpy as np

ar = np.array([[2,6,3],[47,6,33]])
print(np.sort(ar))


[[ 2  3  6]
 [ 6 33 47]]


In [5]:
import numpy as np

ar = np.array([34,56,343,6,7,8,9,10])
#search = print(np.where(ar == 56))
search = print(np.where(ar % 2 == 0 ))
print(earch)

(array([0, 1, 3, 5, 7]),)
None


In [9]:
 import numpy as np

ar = np.array([34,56,343,6])

#fa = [True, False, True, False]

fa = ar>50

new = ar[fa]
print(new)

[ 56 343]
